# Generated by Django 4.2.7 on 2023-12-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0004_catagory_alter_blog_options_blog_calagori_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='calagori_name',
        ),
        migrations.AddField(
            model_name='blog',
            name='catagori_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catagori_blog', to='App_Blog.catagory'),
        ),
    ]
