# Generated by Django 4.2.7 on 2024-01-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0014_tag_catagory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='App_Blog.tag'),
        ),
    ]
