# Generated by Django 4.2.7 on 2024-01-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0015_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_blogs', to='App_Blog.tag'),
        ),
    ]
