# Generated by Django 4.2.7 on 2023-11-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(default='Uploaded/Login_App/default-profile-pic.png', upload_to='Uploaded/Login_App/Profile_Pics/'),
        ),
    ]
